#!/bin/sh

# ignore merge request
MERGE_MSG=`cat $1 | egrep '^Merge branch*'`

if [ "$MERGE_MSG" != "" ]; then
    exit 0
fi

#COMMIT_MSG=`cat $1 | egrep "^(feat|fix|docs|chore|refactor|revert|style|test|build)(\(\w+\))?:\s(\S|\w)+"`
COMMIT_MSG=`cat $1 | egrep "^(feat|fix|docs|chore|refactor|revert|style|test|build):(GPT-[0-9]+):\s(\S|\w)+"`

if [ "$COMMIT_MSG" = "" ]; then
    echo "Commit Message does not comply with conventional commits standards, Please check!\n"
    exit 1
fi

if [ ${#COMMIT_MSG} -lt 15 ]; then
    echo "Commit Message Too Short, Please include story ticket no or issue no. show me more detail!\n"
    exit 1
fi


