// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"grpc-boot-starter/infra/db"
	"grpc-boot-starter/persistence/repository"
	"grpc-boot-starter/services"
)

// Injectors from wire_injector.go:

func InitializeBookService() *services.BookServiceServerImpl {
	bookRepository := repository.NewBookRepository()
	bookServiceServerImpl := services.NewBookServiceServerImpl(bookRepository)
	return bookServiceServerImpl
}

func InitializeHelloService() *services.HelloServiceServerImpl {
	helloServiceServerImpl := services.NewHelloServiceServerImpl()
	return helloServiceServerImpl
}

// wire_injector.go:

// ProviderSet
var dbSet = wire.NewSet(db.GetDBCon)

// bookServiceSet
var bookServiceSet = wire.NewSet(repository.NewBookRepository, services.NewBookServiceServerImpl)

// helloServiceSet
var helloServiceSet = wire.NewSet(services.NewHelloServiceServerImpl)
