// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"grpc-boot-starter/api/controller"
	"grpc-boot-starter/infra/db"
	"grpc-boot-starter/persistence/repository"
	"grpc-boot-starter/service"
)

// Injectors from wire_injector.go:

func InitializeBookService() *service.BookService {
	bookRepository := repository.NewBookRepository()
	bookService := service.NewBookService(bookRepository)
	return bookService
}

func InitializeBookController() *controller.BookControllerImpl {
	bookRepository := repository.NewBookRepository()
	bookService := service.NewBookService(bookRepository)
	bookControllerImpl := controller.NewBookControllerImpl(bookService)
	return bookControllerImpl
}

func InitializeHelloController() *controller.HelloControllerImpl {
	helloControllerImpl := controller.NewHelloControllerImpl()
	return helloControllerImpl
}

// wire_injector.go:

// ProviderSet
var dbSet = wire.NewSet(db.GetDBCon)

// bookServiceSet
var bookServiceSet = wire.NewSet(repository.NewBookRepository, service.NewBookService)
