// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: book_controller.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookControllerService_CreateBook_FullMethodName = "/proto.v1.BookControllerService/CreateBook"
	BookControllerService_UpdateBook_FullMethodName = "/proto.v1.BookControllerService/UpdateBook"
	BookControllerService_DeleteBook_FullMethodName = "/proto.v1.BookControllerService/DeleteBook"
	BookControllerService_GetBook_FullMethodName    = "/proto.v1.BookControllerService/GetBook"
	BookControllerService_QueryBooks_FullMethodName = "/proto.v1.BookControllerService/QueryBooks"
)

// BookControllerServiceClient is the client API for BookControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookControllerServiceClient interface {
	CreateBook(ctx context.Context, in *BookCreateInput, opts ...grpc.CallOption) (*BookInfo, error)
	UpdateBook(ctx context.Context, in *BookUpdateInput, opts ...grpc.CallOption) (*BookInfo, error)
	DeleteBook(ctx context.Context, in *BookDeleteInput, opts ...grpc.CallOption) (*BookDeleteResponse, error)
	GetBook(ctx context.Context, in *BookGetInput, opts ...grpc.CallOption) (*BookInfo, error)
	QueryBooks(ctx context.Context, in *BookQueryInput, opts ...grpc.CallOption) (*BookInfoListResponse, error)
}

type bookControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookControllerServiceClient(cc grpc.ClientConnInterface) BookControllerServiceClient {
	return &bookControllerServiceClient{cc}
}

func (c *bookControllerServiceClient) CreateBook(ctx context.Context, in *BookCreateInput, opts ...grpc.CallOption) (*BookInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookInfo)
	err := c.cc.Invoke(ctx, BookControllerService_CreateBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookControllerServiceClient) UpdateBook(ctx context.Context, in *BookUpdateInput, opts ...grpc.CallOption) (*BookInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookInfo)
	err := c.cc.Invoke(ctx, BookControllerService_UpdateBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookControllerServiceClient) DeleteBook(ctx context.Context, in *BookDeleteInput, opts ...grpc.CallOption) (*BookDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookDeleteResponse)
	err := c.cc.Invoke(ctx, BookControllerService_DeleteBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookControllerServiceClient) GetBook(ctx context.Context, in *BookGetInput, opts ...grpc.CallOption) (*BookInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookInfo)
	err := c.cc.Invoke(ctx, BookControllerService_GetBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookControllerServiceClient) QueryBooks(ctx context.Context, in *BookQueryInput, opts ...grpc.CallOption) (*BookInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookInfoListResponse)
	err := c.cc.Invoke(ctx, BookControllerService_QueryBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookControllerServiceServer is the server API for BookControllerService service.
// All implementations must embed UnimplementedBookControllerServiceServer
// for forward compatibility.
type BookControllerServiceServer interface {
	CreateBook(context.Context, *BookCreateInput) (*BookInfo, error)
	UpdateBook(context.Context, *BookUpdateInput) (*BookInfo, error)
	DeleteBook(context.Context, *BookDeleteInput) (*BookDeleteResponse, error)
	GetBook(context.Context, *BookGetInput) (*BookInfo, error)
	QueryBooks(context.Context, *BookQueryInput) (*BookInfoListResponse, error)
	mustEmbedUnimplementedBookControllerServiceServer()
}

// UnimplementedBookControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookControllerServiceServer struct{}

func (UnimplementedBookControllerServiceServer) CreateBook(context.Context, *BookCreateInput) (*BookInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookControllerServiceServer) UpdateBook(context.Context, *BookUpdateInput) (*BookInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookControllerServiceServer) DeleteBook(context.Context, *BookDeleteInput) (*BookDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedBookControllerServiceServer) GetBook(context.Context, *BookGetInput) (*BookInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookControllerServiceServer) QueryBooks(context.Context, *BookQueryInput) (*BookInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBooks not implemented")
}
func (UnimplementedBookControllerServiceServer) mustEmbedUnimplementedBookControllerServiceServer() {}
func (UnimplementedBookControllerServiceServer) testEmbeddedByValue()                               {}

// UnsafeBookControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookControllerServiceServer will
// result in compilation errors.
type UnsafeBookControllerServiceServer interface {
	mustEmbedUnimplementedBookControllerServiceServer()
}

func RegisterBookControllerServiceServer(s grpc.ServiceRegistrar, srv BookControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookControllerService_ServiceDesc, srv)
}

func _BookControllerService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookControllerServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookControllerService_CreateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookControllerServiceServer).CreateBook(ctx, req.(*BookCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookControllerService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookControllerServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookControllerService_UpdateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookControllerServiceServer).UpdateBook(ctx, req.(*BookUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookControllerService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookDeleteInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookControllerServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookControllerService_DeleteBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookControllerServiceServer).DeleteBook(ctx, req.(*BookDeleteInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookControllerService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookGetInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookControllerServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookControllerService_GetBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookControllerServiceServer).GetBook(ctx, req.(*BookGetInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookControllerService_QueryBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookQueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookControllerServiceServer).QueryBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookControllerService_QueryBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookControllerServiceServer).QueryBooks(ctx, req.(*BookQueryInput))
	}
	return interceptor(ctx, in, info, handler)
}

// BookControllerService_ServiceDesc is the grpc.ServiceDesc for BookControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.BookControllerService",
	HandlerType: (*BookControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookControllerService_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookControllerService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookControllerService_DeleteBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookControllerService_GetBook_Handler,
		},
		{
			MethodName: "QueryBooks",
			Handler:    _BookControllerService_QueryBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book_controller.proto",
}
