// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: hello_controller.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelloControllerService_SayHello_FullMethodName = "/proto.v1.HelloControllerService/SayHello"
)

// HelloControllerServiceClient is the client API for HelloControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloControllerServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloControllerServiceClient(cc grpc.ClientConnInterface) HelloControllerServiceClient {
	return &helloControllerServiceClient{cc}
}

func (c *helloControllerServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HelloControllerService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloControllerServiceServer is the server API for HelloControllerService service.
// All implementations must embed UnimplementedHelloControllerServiceServer
// for forward compatibility.
type HelloControllerServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHelloControllerServiceServer()
}

// UnimplementedHelloControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloControllerServiceServer struct{}

func (UnimplementedHelloControllerServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloControllerServiceServer) mustEmbedUnimplementedHelloControllerServiceServer() {
}
func (UnimplementedHelloControllerServiceServer) testEmbeddedByValue() {}

// UnsafeHelloControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloControllerServiceServer will
// result in compilation errors.
type UnsafeHelloControllerServiceServer interface {
	mustEmbedUnimplementedHelloControllerServiceServer()
}

func RegisterHelloControllerServiceServer(s grpc.ServiceRegistrar, srv HelloControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedHelloControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelloControllerService_ServiceDesc, srv)
}

func _HelloControllerService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloControllerServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloControllerService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloControllerServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloControllerService_ServiceDesc is the grpc.ServiceDesc for HelloControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.HelloControllerService",
	HandlerType: (*HelloControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloControllerService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_controller.proto",
}
