# application
app:
  name: Example test
  profile: test

server:
  port: 8080

datasource:
  url: postgres://postgres:pgdev01@postgres:5432/postgres?sslmode=disable&search_path=bookstore
  driver: "pgx"
  pool:
    max: 10
    min: 5

logging:
  level: debug
  format: plain # json, plain
  output: console # console

otel:
  service:
    name: gin-001
    version: 1.0.0
  insecure: true
  exporter:
    endpoint: localhost:14317 #grpc
    logging: false
    tracer: false
    metrics: false

security:
  jwt:
    private_key: private-key.pem # file, url
    public_key: public-key.pem # file, url
    algorithm: RS512
    issuer: gin001
    keyId: 900150983cd24fb0d6963f7d28e17f72
    expiration: 60 # minutes
    refresh_token_expiration: 72 # hours
    token_blacklist_enabled: true
    token_blacklist_ttl: 30 # minutes