BEGIN;

CREATE TABLE IF NOT EXISTS books (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL DEFAULT '',
	author VARCHAR(100) NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT '',
	price NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    category VARCHAR(100) NOT NULL,
    amount INT NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT TRUE,
    status INT NOT NULL DEFAULT 0,
    deleted boolean NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

COMMIT;