package correlation

import "context"

var (
	TraceIdFieldName       = "trace_id"
	CorrelationIdFieldName = "correlation_id"
	SpanIdFieldName        = "span_id"
	CorrelationCtxKey      = "correlation_ctx_key"
)

type CorrelationCtx struct {
	TraceId string
	SpanId  string
	Id      string
}

// CorrelationId if request having traceId then return traceId
// otherwise return Id generated by server
func CorrelationId(ctx context.Context) string {
	v := ctx.Value(CorrelationCtxKey)
	if v == nil {
		return ""
	}
	s := v.(*CorrelationCtx).TraceId
	if s != "" {
		return s
	}
	return v.(*CorrelationCtx).Id
}

func TraceId(ctx context.Context) string {
	v := ctx.Value(CorrelationCtxKey)
	if v == nil {
		return ""
	}
	return v.(*CorrelationCtx).TraceId
}

func SpanId(ctx context.Context) string {
	v := ctx.Value(CorrelationCtxKey)
	if v == nil {
		return ""
	}
	return v.(*CorrelationCtx).SpanId
}
